#!/usr/bin/env bash
#
# Build and launch the Soul browser.
#
# Usage:
#   Scripts/build_and_run.sh [options]
#
# Options:
#   -c, --configuration <Debug|Release>  Build configuration (default: Debug)
#       --clean                          Clean before building (slower, but safe)
#       --no-gen                         Skip XcodeGen project regeneration
#       --no-run                         Build only; don't launch the app
#   -h, --help                           Show this help and exit
#
# Notes:
#   * The project is generated by XcodeGen from project.yml. Whenever a source
#     file is added or removed, the .xcodeproj must be regenerated or the new
#     file won't be compiled. This script does that for you by default.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

PROJECT="Soul.xcodeproj"
SCHEME="Soul"
CONFIG="Debug"
DO_GEN=1
DO_CLEAN=0
DO_RUN=1

usage() { sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    -c|--configuration) CONFIG="${2:?missing value for $1}"; shift 2 ;;
    --clean)            DO_CLEAN=1; shift ;;
    --no-gen)           DO_GEN=0; shift ;;
    --no-run)           DO_RUN=0; shift ;;
    -h|--help)          usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

# 1. Regenerate the Xcode project so newly added/removed sources are picked up.
if [[ $DO_GEN -eq 1 ]]; then
  if command -v xcodegen >/dev/null 2>&1; then
    echo "==> Regenerating $PROJECT (XcodeGen)"
    xcodegen generate
  else
    echo "==> xcodegen not found; skipping regeneration (brew install xcodegen)" >&2
  fi
fi

# 2. Build.
BUILD_ACTIONS=(build)
[[ $DO_CLEAN -eq 1 ]] && BUILD_ACTIONS=(clean build)
echo "==> Building $SCHEME ($CONFIG)"
xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration "$CONFIG" \
  CODE_SIGNING_ALLOWED=NO "${BUILD_ACTIONS[@]}"

# 3. Resolve the built .app path from the build settings (don't hard-code it).
SETTINGS="$(xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration "$CONFIG" \
  -showBuildSettings CODE_SIGNING_ALLOWED=NO 2>/dev/null)"
PRODUCTS_DIR="$(awk -F' = ' '/ BUILT_PRODUCTS_DIR /{print $2; exit}' <<<"$SETTINGS")"
APP_NAME="$(awk -F' = ' '/ FULL_PRODUCT_NAME /{print $2; exit}' <<<"$SETTINGS")"
APP="$PRODUCTS_DIR/$APP_NAME"

if [[ ! -d "$APP" ]]; then
  echo "Build succeeded but app not found at: $APP" >&2
  exit 1
fi

# 4. Relaunch: quit any running instance (main app + CEF helpers), then open.
if [[ $DO_RUN -eq 1 ]]; then
  echo "==> Relaunching $APP"
  pkill -x Soul 2>/dev/null || true
  pkill -f "Soul Helper" 2>/dev/null || true
  sleep 1
  open "$APP"
  echo "Launched: $APP"
else
  echo "Built: $APP"
fi
